### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by telmer6** [gerbera/gerbera.io#1]
Having just stumbled upon Gerbera, there is an off-putting lack of documentation. While plenty of information is present to install Gerbera, there is no easily-discoverable instruction on how to use/configure the program, especially as a service. The closest I can find to any actual documentation is the old readme for MediaTomb.

This issue was created on the gerbera.io repo rather than gerbera itself, as the manpage directs the user (rather unhelpfully) to gerbera.io .

**Comment by v00d00** [comment]
There is stuff on docs.gerbera.io now 👍
