### ISSUE TITLE
gerbera and mysql

### ISSUE THREAD

**Issue by frpatte2** [gerbera/gerbera.io#2]
I have just compiled gerbera, enabling mysql database, but it doesn't work: the database is created but is not usable, trying to open gerbera with vlc gives this error message:

INFO: Exception: Mysql: mysql_real_query() failed: mysql_error (1235): "This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'"; query: SELECT `id` FROM `mt_cds_object` WHERE ( `dc_title`LIKE 'cover.jp%' OR `dc_title`LIKE 'albumart%.jp%' OR `dc_title`LIKE 'album.jp%' OR `dc_title`LIKE 'front.jp%' OR `dc_title`LIKE 'folder.jp%' ) AND `upnp_class`='object.item.imageItem' AND ( ( `parent_id` IN (SELECT `parent_id` FROM `mt_cds_object` WHERE `upnp_class`='object.item.audioItem.musicTrack' AND `id` IN (SELECT `ref_id` FROM `mt_cds_object` WHERE `parent_id`='1' AND `object_type`=2 LIMIT 100))     ) OR `parent_id`='1') LIMIT 1

What a mere mortal like me can do?

Thank you.

**Comment by elmodaddyb** [comment]
Hey @frpatte2 sorry to hear of the trouble.  It looks like the MariaDB approach would be to use a **JOIN** statement. This would likely require code change. 

You _could_ use SQLite if that is available to you. The system auto generates a config.xml filesystem that you can adjust.

**Comment by v00d00** [comment]
Hi @frpatte2 if this is still an issue you will need to open an issue at the [main repo](https://github.com/gerbera/gerbera).
