### ISSUE TITLE
Gerbera available on OpenWrt

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera.io#7]
http://docs.gerbera.io/en/latest/install.html points to gerbera in a bunch of places. It's also available in OpenWrt 19.07 (version 1.4.0) and in the current development version as 1.5.0. (Cannot backport 1.5.0 as GCC7 is being used).

Installable with

```
opkg update
opkg install gerbera
```

**Comment by neheb** [comment]
ping @whyman 

OpenWrt 19.07 (stable) includes 1.4.0.

OpenWrt 20.xx (next version) as of now will have Gerbera 1.6.1.

**Comment by whyman** [comment]
This awesome @neheb!

Can you submit a PR to update the docs?
