### ISSUE TITLE
Gerbera 1.8.2 crash while trying to start with Haiku 64bit hrev55152

### ISSUE THREAD

**Issue by Brunobasta** [gerbera/gerbera.io#9]
Crash just at start:
http://0x0.st/-LVJ.png

There is a bug report:
Hope this helps?
https://pastebin.com/y3e4zWiq

**Comment by Brunobasta** [comment]
If the browser is open. It will work but it says: The system encountered an error! 
There is no way to log in. The login button is not visiblle?

**Comment by KarlStraussberger** [comment]
Already exists in code rep
